adding new reminder pack codes
ONSdigital/census-rm-action-processor pull request #13
Opened 2020-08-04 23:12 UTC by apolloakora

# Motivation and Context
Adding a host of new reminder pack codes in order to align the code with this [confluence document](https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Census+Reminder+Run+Book+-+2021)

# What has changed
Action type has changed. Some small refactoring has occurred to align the ActionType classes across worker, scheduler and processor.

2020-08-04 23:16 UTC, apolloakora commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add reminder pack codes (3)](https://trello.com/c/6qsTSOf5/1118-add-reminder-pack-codes-3)

2020-08-05 11:40 UTC, NickGrantX requested changes
~Missing pack code: P_RL_1RL1_1~

2020-08-07 07:02 UTC, NickGrantX approved these changes

2020-08-07 12:33 UTC, AdamHawtin approved these changes
LGTM, passes AT's 👍

2020-08-12 14:31 UTC, merged